server:
  port: 88
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
#        - id: test_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url,baidu
#        - id: test_qq
#          uri: https://www.qq.com
#          predicates:
#              - Query=url,qq

        - id: product_route
          uri: lb://gulimall-product
          predicates:
              - Path=/api/product/**
          filters:
              - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id:  coupon_route
          uri: lb://gulimall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
             - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: thirdparty_route
          uri: lb://gulimall-thirdparty
          predicates:
              - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*), /$\{segment}


        - id: admin_route
          uri: lb://renren-fast
          predicates:
              - Path=/api/**
          filters:
              - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}

        - id: gulimall_host_route
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com,item.gulimall.com

        - id: gulimall-auth-route
          uri: lb://gulimall-auth
          predicates:
            - Host=auth.gulimall.com

        - id: gulimall_search_host_route
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com

        - id: gulimall_cart_host_route
          uri: lb://gulimall-cart
          predicates:
            - Host=cart.gulimall.com

        - id: gulimall_order_host_route
          uri: lb://gulimall-order
          predicates:
            - Host=order.gulimall.com

        - id: gulimall_member_host_route
          uri: lb://gulimall-member
          predicates:
            - Host=member.gulimall.com

        - id: gulimall_seckill_host_route
          uri: lb://gulimall-seckill
          predicates:
            - Host=seckill.gulimall.com